from typing import Protocol

from src.domain.entities.book import Book
from src.domain.entities.user import User


class EncoderProtocol(Protocol):
    def build_context(self, users: list[User], books: list[Book]) -> dict: ...
    def encode_user(self, user: User, context: dict) -> list[float]: ...
    def encode_book(self, book: Book, context: dict) -> list[float]: ...
    def encode_user_book_query(self, user: User, context: dict) -> list[float]: ...
    def create_training_data(self, users: list[User], books: list[Book], context: dict): ...
