from typing import Protocol


class ModelRepositoryProtocol(Protocol):
    def build_and_train(self, xs, ys, input_dim: int): ...
    def save(self, model) -> None: ...
    def load(self): ...
    def predict(self, model, xs): ...
    def save_context(self, context: dict) -> None: ...
    def load_context(self) -> dict | None: ...
