from typing import Protocol


class VectorStoreProtocol(Protocol):
    def upsert_user(self, user_id: str, vector: list[float], payload: dict) -> None: ...
    def upsert_book(self, book_id: str, vector: list[float], payload: dict) -> None: ...
    def search_books(self, query_vector: list[float], limit: int = 50) -> list[str]: ...
